name: Upload distribution to PyPI

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this release
        draft: false
        prerelease: false
  deploy:
    name: Publish distribution to PyPI
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Python 3.9
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Update pip
      run: python -m pip install -U pip
    - name: Install pypa/build
      run: python -m pip install -U build --user
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}